sudo: required
dist: trusty
language: go
env:
  - GIMME_OS=linux GIMME_ARCH=amd64 PATH=$TRAVIS_BUILD_DIR/linux_amd64:$PATH
go:
  - 1.6
before_install:
  # Install the arm32 cross-compiler
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu zesty main'
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gcc-arm-linux-gnueabi
  - arm-linux-gnueabi-gcc --version
  - sudo apt-get install -qq -y gcc-arm-linux-gnueabihf
  - arm-linux-gnueabihf-gcc --version
  # Install golang
  - gimme 1.6
  # Correct rake bug
  - RAKE=`which rake`
  - mv `which rake` `which rake`.old
  - touch ${RAKE}
  - chmod 755 ${RAKE}
install:
  - dep ensure
  - find vendor
  # Module build
  - source /home/travis/.gimme/envs/go1.9.env
  - which go
  - go version
  # Glide last
  - cd $TRAVIS_BUILD_DIR
  - ls -lrt
  - make all
deploy:
  provider: releases
  overwrite: true
  api_key: "$GITHUB_OAUTH2_KEY"
  file:
  - "${GOPATH}/jarvis-rest-module-0.0.1-SNAPSHOT.armel"
  - "${GOPATH}/jarvis-rest-module-0.0.1-SNAPSHOT.armhf"
  - "${TRAVIS_BUILD_DIR}/script/jarvis-go-service"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy: echo "deploiement terminé"